//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidChef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int reviewID { get; set; }
        public int userID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> stars { get; set; }
        public Nullable<int> tagID { get; set; }
    }
}
